### ISSUE TITLE
Add citation information?

### ISSUE THREAD

**Issue by jbusecke** [SciTools/nc-time-axis#104]
I am trying to cite this amazing tool in a paper revision and noticed this does not have any citation info? 
Would it be possible to mint a DOI via e.g. zenodo?
That way I could cite it properly in the final version of the paper.

**Comment by spencerkclark** [comment]
Thanks @jbusecke!  It seems like it should be possible.  It looks like [SciTools/iris does this](https://zenodo.org/record/6347182).  Is there any kind of special guidance from @SciTools regarding minting Zenodo DOIs, or is simply following [the generic process described in the GitHub docs](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) sufficient?

**Comment by trexfeathers** [comment]
It could be that there are now better solutions out there, newer than Iris' solution. I will raise this at my team meeting tomorrow to see what folks think.

**Comment by spencerkclark** [comment]
Thanks @trexfeathers!

**Comment by jbusecke** [comment]
Awesome. Thanks @trexfeathers and @spencerkclark.

**Comment by spencerkclark** [comment]
@trexfeathers sorry I don't want to lose track of this -- was there any news from the team meeting on this front?

**Comment by trexfeathers** [comment]
Ah, sorry folks! 'Spinning too many plates'.

We're happy with Zenodo. @spencerkclark you have as many permissions as I have, so feel free to have a go with GitHub's Zenodo instructions that you linked. If you run into any problems we'll get one of the SciTools 'responsible adults' to press the appropriate buttons.

**Comment by spencerkclark** [comment]
No worries, thanks @trexfeathers!  I'll give it a go some time in the next few days and will let you know if I run into any issues.

**Comment by spencerkclark** [comment]
I flipped the switch in Zenodo to enable DOIs to be minted automatically upon new releases.  I can't seem to find a seamless way to mint a DOI for an existing release, so we may need to make a new minor one to address this.  It might be good to address #97 at the same time, so I went ahead and made a PR.

**Comment by spencerkclark** [comment]
Sorry I let this slip for a bit.  With #97 now closed, if there are no objections I’ll go ahead and make a v1.4.1 release this week.

**Comment by spencerkclark** [comment]
The release is in progress -- I am still waiting on the automatic conda-forge PR to be opened -- but I cut the release on GitHub and the Zenodo DOI was created (see [here](https://zenodo.org/record/6472641#.Yl_ygS-B2M4))!  

Do you also recommend we create [a `CITATION.cff` file](https://citation-file-format.github.io/about/)?  At a minimum I will add the Zenodo badge to the README (https://github.com/SciTools/nc-time-axis/pull/110).

**Comment by jbusecke** [comment]
I thought the CITATION.cff was required by zenodo these days? I have started adding it, since it usually is a bit more reliable with names and adds a link to ORCID which is very handy.

**Comment by spencerkclark** [comment]
> I thought the CITATION.cff was required by zenodo these days?

There is no requirement as far as I can tell based on [the Zenodo instructions](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content).  But in hindsight it does seem like they try to integrate it now if a repository has a `CITATION.cff` file (I can't seem to find this documented [anywhere but twitter](https://twitter.com/zenodo_org/status/1420357001490706442?lang=en)).

We can add one here and I presume it will take that author metadata into account upon the next release.  It will take a moment to collect it from all the contributors.

**Comment by jbusecke** [comment]
Yes we have just been going through that process over at https://github.com/xgcm/xgcm/issues/449. No rush from my end.

**Comment by bjlittle** [comment]
Hey @jbusecke and @spencerkclark,

PR #129 will add a `CITATION.cff` to the repo, so this should help matters. Along with the `Zenodo` service being enables, I think we're now in a happier place :smile: 

Once PR #129 lands, I'll create a pinned issue and `@` all contributors to `nc-time-axis` asking them to add their ORCID credentials to the file (if they want).

HTH :+1:
