### ISSUE TITLE
Request for contributor ORCIDs

### ISSUE THREAD

**Issue by bjlittle** [SciTools/nc-time-axis#135]
## 📰 Custom Issue

Dear awesome `nc-time-axis` contributors!

`nc-time-axis` is now citable and contains a [CITATION.cff](https://github.com/SciTools/nc-time-axis/blob/main/CITATION.cff) file.

If you'd like to be recognised as a citable contributor then please share your [ORCID](https://orcid.org/) details in a comment in this issue, and I'll add them in batch to the `CITATION.cff`. Alternatively, if you want to raise a pull-request yourself instead, then go for it... whatever you prefer :+1: 

If you don't want to add your details, then that's also totally fine too.

Regardless, thanks for caring and contributing to `nc-time-axis` :beers: 

Hopefully, I've not missed anyone from the list:

- [x] @aulemahal 
- [x] @bjlittle
- [ ] @DPeterK 
- [x] @jbusecke 
- [x] @lbdreyer
- [ ] @marqh 
- [ ] @mbeedie 
- [x] @ocefpaf 
- [x] @pelson 
- [x] @rcomer 
- [x] @spencerkclark 
- [x] @trexfeathers

**Comment by pelson** [comment]
ORCID: 0000-0001-6360-749X

**Comment by spencerkclark** [comment]
Thanks @bjlittle!  My ORCID is: 0000-0001-5595-7895.

**Comment by jbusecke** [comment]
Thanks a lot @bjlittle. My orcid is 0000-0001-8571-865X

**Comment by aulemahal** [comment]
Thanks! Mine is 0000-0003-1192-0403

**Comment by lbdreyer** [comment]
My ORCID is 0009-0006-6310-3658

**Comment by ocefpaf** [comment]
Thanks @bjlittle!

0000-0003-4165-2913

**Comment by bjlittle** [comment]
Chatting offline @rcomer provided her ORCID

0009-0007-5336-0244

Thanks! :beers:

**Comment by trexfeathers** [comment]
[`0009-0000-6857-560X`](https://orcid.org/0009-0000-6857-560X)

**Comment by bjlittle** [comment]
I'm going to close this issue now. 

If you want to have your ORCID added to the `CITATION.cff` then please raise and issue or pull-request and we'll service it ASAP 👍
