### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ocefpaf** [SciTools/nc-time-axis#35]
https://github.com/SciTools/iris/pull/3016 is blocked b/c we need a new release of `nc-time-axis` with #30

**Comment by pelson** [comment]
Just cut in https://github.com/SciTools/nc-time-axis/releases/tag/v1.1.0.

Thanks for the awesome stuff @ocefpaf!

**Comment by ocefpaf** [comment]
Thanks! I'll send a PR to `conda-forge`.
