### ISSUE TITLE
pypi submission no description

### ISSUE THREAD

**Issue by pelson** [SciTools/nc-time-axis#36]
As per https://pypi.org/project/nc-time-axis/1.1.0/:

```
The author of this package has not provided a project description
```

It would be great to update the README to markdown at the same time. Similar effort was done in https://github.com/SciTools/cf_units/pull/103.

@LukeC92 was involved in doing a similar thing for iris-grib recently, and may like to have a go at this one too.

**Comment by bjlittle** [comment]
Closed by #66
