### ISSUE TITLE
release on pip?

### ISSUE THREAD

**Issue by rabernat** [SciTools/nc-time-axis#43]
We noticed that pypi version of nc-time-axis is still at 1.1.0:
https://pypi.org/project/nc-time-axis/

Would be great to keep that up to date with conda.

**Comment by bjlittle** [comment]
@rabernat Yup, guilty as charged :cold_sweat: 

Thanks for the nudge, we'll sort that out. Apologies

**Comment by bjlittle** [comment]
@rabernat All done, enjoy [nc-time-axis 1.2.0](https://pypi.org/project/nc-time-axis/) on PyPi ... finally :wink:

Apologies, once again - we'll stay on top of future releases.

**Comment by bjlittle** [comment]
Ping @lbdreyer

**Comment by rabernat** [comment]
Thanks so much for this!

FZI, we have dozens of new users at the [https://cmip6hack.github.io](CMIP6 hackathon) using nc_time_axis for the first time and loving it! Thanks for this excellent and broadly useful tool.

(Or more accurately, they are plotting data from all kinds of different calendars and it "just works." So they don't even notice nc_time_axis, which is the mark of truly great software! 😄 )
