### ISSUE TITLE
small change to tests needed for upcoming cftime 1.3.0 release

### ISSUE THREAD

**Issue by jswhit2** [SciTools/nc-time-axis#52]
PR #51 will ensure the tests pass with cftime >= 1.3.0.

cftime 1.3.0 will allow vanilla cftime.datetime instances to be calendar-specific using the calendar `__init__` kwarg (the calendar specific sub-classes will no longer be required to instantiate 'calendar-aware' instances).

**Comment by jswhit** [comment]
cftime 1.3.0 has been release, and this apparently breaks nc-time-axis (see https://github.com/Unidata/cftime/issues/210)

**Comment by bjlittle** [comment]
Closed by #66
