### ISSUE TITLE
Cannot import nc_time_axis (v1.2.0, python v3.8.5, conda environment)

### ISSUE THREAD

**Issue by nelerey** [SciTools/nc-time-axis#53]
(This may also be a problem with conda rather than nc-time-axis, but I'm posting here as it is the only package for which this problem occurs.)

I have nc-time-axis installed (v1.2.0, build: py_1, channel: conda-forge), mainly to use it with xarray. 
However, running `import nc_time_axis` results in `ModuleNotFoundError: No module named 'nc_time_axis'`. 

The conda environment in which nc-time-axis is installed is activated when this error occurs, and has python v3.8.5. OS: linux (hpc)

Is this likely to be a problem with nc-time-axis?

**Comment by ocefpaf** [comment]
I just tested the package and it worked for me on Linux in a fresh env:

```
conda create --name TEST python=3.8 nc-time-axis
conda activate TEST
python -c "import nc_time_axis; print(nc_time_axis.__version__)"
1.2.0
```

Please open an issue at https://github.com/conda-forge/nc_time_axis-feedstock and fill the required debug information. It is probably something in your env and the info you will fill in there may help us find it.
