### ISSUE TITLE
New minor release?

### ISSUE THREAD

**Issue by jbusecke** [SciTools/nc-time-axis#54]
Would it be possible to release a new minor version to pypi/conda-forge which includes #50? I would love to have this feature in my normal production environments.

Happy to help with this too!

**Comment by trexfeathers** [comment]
@jbusecke it's on our radar to get a new release out given the problems with cftime v1.3.0. Unfortunately resources for this are tight at the moment so not sure of a timeline yet.

It would definitely need #51 to be in there but that seems to have stalled (https://github.com/SciTools/nc-time-axis/pull/51#issuecomment-762121068). Do you fancy finishing that off?

**Comment by jbusecke** [comment]
I will definitely take a look. Given my snail tempo of working with the test framework last time, I cannot promise anything 😆

**Comment by bjlittle** [comment]
@jbusecke We're now committed to making an `nc-time-axis` 1.3.0 release (finally), see this [v1.3.x release discussion].

Are you happy for me to close this issue, on the promise that we're committed to scheduling a minor release?

**Comment by bjlittle** [comment]
No worries. It's high time that we showed some love to `nc-time-axis`. Thanks for being so patient :beers:
