### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bjlittle** [SciTools/nc-time-axis#62]
## 📚 Documentation
The `nc-time-axis` project needs some basic documentation on readthedocs to help the community understand what the package is and how to use it.

**Comment by spencerkclark** [comment]
I made a start on the infrastructure required for this in #87.  I went ahead and used the [sphinx RTD theme](https://sphinx-rtd-theme.readthedocs.io/en/stable/) and configured Read the Docs such that preview documentation will be built with every pull request, which should hopefully make it easier to iterate on and review PRs that impact documentation.  See [here](https://nc-time-axis--87.org.readthedocs.build/en/87/) for how it looks currently.

@SciTools/nc-time-axis-devs let me know if you have any issues with this approach.  In the meantime I'll get started on filling it out with some content.
