### ISSUE TITLE
Deprecate `CalendarDateTime`?

### ISSUE THREAD

**Issue by spencerkclark** [SciTools/nc-time-axis#81]
`CalendarDateTime` served a purpose in the early days of nc-time-axis, but I now think it may not be needed anymore, particularly once #75 is addressed (#80).  `cftime.datetime` instances now have a meaningful `calendar` attribute and their comparisons now check that calendars and datetime components are equal.  Should we include a `DeprecationWarning` in the next release of nc-time-axis?

As an aside, reading some of the existing tests for `CalendarDateTime` makes me a little uneasy now that `cftime.datetime` objects have a default calendar of `"gregorian"` instead of `None`:
https://github.com/SciTools/nc-time-axis/blob/59c567d307eb8ced44f2c95b393c93ba571e486c/nc_time_axis/tests/unit/test_NetCDFTimeConverter.py#L116-L121
Apparently these still pass despite the fact that the `calendar` of the datetime object does not match the calendar of the `CalendarDateTime` object.

**Comment by aulemahal** [comment]
Agreed. It's become useless with your PR and the new cftime, it only increases the chance of bugs like the one you pointed out...
